function [Veh] = Vehicle_2A3(Veh)
% Vehicle_2A3
% Created: 10-Oct-2022 17:56:46
 
% -- Vehicle information --
% num_axles_per_body = [2  3];
% num_axles_per_group = [1  1  1  1  1];
% with_articulation = [1];
 
% -- Vehicle variables --
% Veh.Prop.mBi = [[mB1, mB2]]
% Veh.Prop.IBi = [[IB1, IB2]]
% Veh.Prop.kSj = [[kS1, kS2, kS3, kS4, kS5]]
% Veh.Prop.cSj = [[cS1, cS2, cS3, cS4, cS5]]
% Veh.Prop.mGj = [[mG1, mG2, mG3, mG4, mG5]]
% Veh.Prop.kTk = [[kT1, kT2, kT3, kT4, kT5]]
% Veh.Prop.cTk = [[cT1, cT2, cT3, cT4, cT5]]
% Veh.Prop.ai = [[a1, a2]]
% Veh.Prop.bi = [b1]
% Veh.Prop.dj = [[d1, d2, d3, d4, d5]]
 
% -- Degrees of Freedom --
Veh.DOF(1).name = 'yB1'; Veh.DOF(1).type = 'displacement'; Veh.DOF(1).dependency = 'independent';
Veh.DOF(2).name = 'thetaB1'; Veh.DOF(2).type = 'rotation'; Veh.DOF(2).dependency = 'independent';
Veh.DOF(3).name = 'thetaB2'; Veh.DOF(3).type = 'rotation'; Veh.DOF(3).dependency = 'independent';
Veh.DOF(4).name = 'yG1'; Veh.DOF(4).type = 'displacement'; Veh.DOF(4).dependency = 'independent';
Veh.DOF(5).name = 'yG2'; Veh.DOF(5).type = 'displacement'; Veh.DOF(5).dependency = 'independent';
Veh.DOF(6).name = 'yG3'; Veh.DOF(6).type = 'displacement'; Veh.DOF(6).dependency = 'independent';
Veh.DOF(7).name = 'yG4'; Veh.DOF(7).type = 'displacement'; Veh.DOF(7).dependency = 'independent';
Veh.DOF(8).name = 'yG5'; Veh.DOF(8).type = 'displacement'; Veh.DOF(8).dependency = 'independent';
Veh.DOF(1).num_independent = 8;
 
% -- DOF relations -- 
Veh.DOF(9).name = 'yB2'; Veh.DOF(9).type = 'displacement'; Veh.DOF(9).dependency = 'dependent';
Veh.DOF(9).expression = 'yB2 = yB1 + a2*thetaB2 + b1*thetaB1';
Veh.DOF(9).fun = @(y) y(1) + Veh.Prop.ai(2)*y(3) + Veh.Prop.bi(1)*y(2);
Veh.DOF(1).num_dependent = 1;
 
% -- Axle spacing and distance --
Veh.Prop.ax_sp = [0, Veh.Prop.dj(2) - Veh.Prop.dj(1), Veh.Prop.ai(2) + Veh.Prop.bi(1) - Veh.Prop.dj(2) + Veh.Prop.dj(3), Veh.Prop.dj(4) - Veh.Prop.dj(3), Veh.Prop.dj(5) - Veh.Prop.dj(4)];
Veh.Prop.ax_dist = [0, Veh.Prop.dj(2) - Veh.Prop.dj(1), Veh.Prop.ai(2) + Veh.Prop.bi(1) - Veh.Prop.dj(1) + Veh.Prop.dj(3), Veh.Prop.ai(2) + Veh.Prop.bi(1) - Veh.Prop.dj(1) + Veh.Prop.dj(4), Veh.Prop.ai(2) + Veh.Prop.bi(1) - Veh.Prop.dj(1) + Veh.Prop.dj(5)];
 
% -- Vehicle system matrices --
Veh.SysM.M = ...
    [[Veh.Prop.mBi(1) + Veh.Prop.mBi(2), Veh.Prop.bi(1)*Veh.Prop.mBi(2), Veh.Prop.ai(2)*Veh.Prop.mBi(2), 0, 0, 0, 0, 0]; ...
    [Veh.Prop.bi(1)*Veh.Prop.mBi(2), Veh.Prop.IBi(1) + Veh.Prop.bi(1)^2*Veh.Prop.mBi(2), Veh.Prop.ai(2)*Veh.Prop.bi(1)*Veh.Prop.mBi(2), 0, 0, 0, 0, 0]; ...
    [Veh.Prop.ai(2)*Veh.Prop.mBi(2), Veh.Prop.ai(2)*Veh.Prop.bi(1)*Veh.Prop.mBi(2), Veh.Prop.IBi(2) + Veh.Prop.ai(2)^2*Veh.Prop.mBi(2), 0, 0, 0, 0, 0]; ...
    [0, 0, 0, Veh.Prop.mGj(1), 0, 0, 0, 0]; ...
    [0, 0, 0, 0, Veh.Prop.mGj(2), 0, 0, 0]; ...
    [0, 0, 0, 0, 0, Veh.Prop.mGj(3), 0, 0]; ...
    [0, 0, 0, 0, 0, 0, Veh.Prop.mGj(4), 0]; ...
    [0, 0, 0, 0, 0, 0, 0, Veh.Prop.mGj(5)]];
 
Veh.SysM.C = ...
    [[Veh.Prop.cSj(1) + Veh.Prop.cSj(2) + Veh.Prop.cSj(3) + Veh.Prop.cSj(4) + Veh.Prop.cSj(5), Veh.Prop.bi(1)*Veh.Prop.cSj(3) + Veh.Prop.bi(1)*Veh.Prop.cSj(4) + Veh.Prop.bi(1)*Veh.Prop.cSj(5) + Veh.Prop.cSj(1)*Veh.Prop.dj(1) + Veh.Prop.cSj(2)*Veh.Prop.dj(2), Veh.Prop.ai(2)*Veh.Prop.cSj(3) + Veh.Prop.ai(2)*Veh.Prop.cSj(4) + Veh.Prop.ai(2)*Veh.Prop.cSj(5) + Veh.Prop.cSj(3)*Veh.Prop.dj(3) + Veh.Prop.cSj(4)*Veh.Prop.dj(4) + Veh.Prop.cSj(5)*Veh.Prop.dj(5), -Veh.Prop.cSj(1), -Veh.Prop.cSj(2), -Veh.Prop.cSj(3), -Veh.Prop.cSj(4), -Veh.Prop.cSj(5)]; ...
    [Veh.Prop.bi(1)*Veh.Prop.cSj(3) + Veh.Prop.bi(1)*Veh.Prop.cSj(4) + Veh.Prop.bi(1)*Veh.Prop.cSj(5) + Veh.Prop.cSj(1)*Veh.Prop.dj(1) + Veh.Prop.cSj(2)*Veh.Prop.dj(2), Veh.Prop.bi(1)^2*Veh.Prop.cSj(3) + Veh.Prop.bi(1)^2*Veh.Prop.cSj(4) + Veh.Prop.bi(1)^2*Veh.Prop.cSj(5) + Veh.Prop.cSj(1)*Veh.Prop.dj(1)^2 + Veh.Prop.cSj(2)*Veh.Prop.dj(2)^2, Veh.Prop.ai(2)*Veh.Prop.bi(1)*Veh.Prop.cSj(3) + Veh.Prop.ai(2)*Veh.Prop.bi(1)*Veh.Prop.cSj(4) + Veh.Prop.ai(2)*Veh.Prop.bi(1)*Veh.Prop.cSj(5) + Veh.Prop.bi(1)*Veh.Prop.cSj(3)*Veh.Prop.dj(3) + Veh.Prop.bi(1)*Veh.Prop.cSj(4)*Veh.Prop.dj(4) + Veh.Prop.bi(1)*Veh.Prop.cSj(5)*Veh.Prop.dj(5), -Veh.Prop.cSj(1)*Veh.Prop.dj(1), -Veh.Prop.cSj(2)*Veh.Prop.dj(2), -Veh.Prop.bi(1)*Veh.Prop.cSj(3), -Veh.Prop.bi(1)*Veh.Prop.cSj(4), -Veh.Prop.bi(1)*Veh.Prop.cSj(5)]; ...
    [Veh.Prop.ai(2)*Veh.Prop.cSj(3) + Veh.Prop.ai(2)*Veh.Prop.cSj(4) + Veh.Prop.ai(2)*Veh.Prop.cSj(5) + Veh.Prop.cSj(3)*Veh.Prop.dj(3) + Veh.Prop.cSj(4)*Veh.Prop.dj(4) + Veh.Prop.cSj(5)*Veh.Prop.dj(5), Veh.Prop.ai(2)*Veh.Prop.bi(1)*Veh.Prop.cSj(3) + Veh.Prop.ai(2)*Veh.Prop.bi(1)*Veh.Prop.cSj(4) + Veh.Prop.ai(2)*Veh.Prop.bi(1)*Veh.Prop.cSj(5) + Veh.Prop.bi(1)*Veh.Prop.cSj(3)*Veh.Prop.dj(3) + Veh.Prop.bi(1)*Veh.Prop.cSj(4)*Veh.Prop.dj(4) + Veh.Prop.bi(1)*Veh.Prop.cSj(5)*Veh.Prop.dj(5), Veh.Prop.ai(2)^2*Veh.Prop.cSj(3) + Veh.Prop.ai(2)^2*Veh.Prop.cSj(4) + Veh.Prop.ai(2)^2*Veh.Prop.cSj(5) + Veh.Prop.cSj(3)*Veh.Prop.dj(3)^2 + Veh.Prop.cSj(4)*Veh.Prop.dj(4)^2 + Veh.Prop.cSj(5)*Veh.Prop.dj(5)^2 + 2*Veh.Prop.ai(2)*Veh.Prop.cSj(3)*Veh.Prop.dj(3) + 2*Veh.Prop.ai(2)*Veh.Prop.cSj(4)*Veh.Prop.dj(4) + 2*Veh.Prop.ai(2)*Veh.Prop.cSj(5)*Veh.Prop.dj(5), 0, 0, - Veh.Prop.ai(2)*Veh.Prop.cSj(3) - Veh.Prop.cSj(3)*Veh.Prop.dj(3), - Veh.Prop.ai(2)*Veh.Prop.cSj(4) - Veh.Prop.cSj(4)*Veh.Prop.dj(4), - Veh.Prop.ai(2)*Veh.Prop.cSj(5) - Veh.Prop.cSj(5)*Veh.Prop.dj(5)]; ...
    [-Veh.Prop.cSj(1), -Veh.Prop.cSj(1)*Veh.Prop.dj(1), 0, Veh.Prop.cSj(1) + Veh.Prop.cTk(1), 0, 0, 0, 0]; ...
    [-Veh.Prop.cSj(2), -Veh.Prop.cSj(2)*Veh.Prop.dj(2), 0, 0, Veh.Prop.cSj(2) + Veh.Prop.cTk(2), 0, 0, 0]; ...
    [-Veh.Prop.cSj(3), -Veh.Prop.bi(1)*Veh.Prop.cSj(3), - Veh.Prop.ai(2)*Veh.Prop.cSj(3) - Veh.Prop.cSj(3)*Veh.Prop.dj(3), 0, 0, Veh.Prop.cSj(3) + Veh.Prop.cTk(3), 0, 0]; ...
    [-Veh.Prop.cSj(4), -Veh.Prop.bi(1)*Veh.Prop.cSj(4), - Veh.Prop.ai(2)*Veh.Prop.cSj(4) - Veh.Prop.cSj(4)*Veh.Prop.dj(4), 0, 0, 0, Veh.Prop.cSj(4) + Veh.Prop.cTk(4), 0]; ...
    [-Veh.Prop.cSj(5), -Veh.Prop.bi(1)*Veh.Prop.cSj(5), - Veh.Prop.ai(2)*Veh.Prop.cSj(5) - Veh.Prop.cSj(5)*Veh.Prop.dj(5), 0, 0, 0, 0, Veh.Prop.cSj(5) + Veh.Prop.cTk(5)]];
 
Veh.SysM.K = ...
    [[Veh.Prop.kSj(1) + Veh.Prop.kSj(2) + Veh.Prop.kSj(3) + Veh.Prop.kSj(4) + Veh.Prop.kSj(5), Veh.Prop.bi(1)*Veh.Prop.kSj(3) + Veh.Prop.bi(1)*Veh.Prop.kSj(4) + Veh.Prop.bi(1)*Veh.Prop.kSj(5) + Veh.Prop.dj(1)*Veh.Prop.kSj(1) + Veh.Prop.dj(2)*Veh.Prop.kSj(2), Veh.Prop.ai(2)*Veh.Prop.kSj(3) + Veh.Prop.ai(2)*Veh.Prop.kSj(4) + Veh.Prop.ai(2)*Veh.Prop.kSj(5) + Veh.Prop.dj(3)*Veh.Prop.kSj(3) + Veh.Prop.dj(4)*Veh.Prop.kSj(4) + Veh.Prop.dj(5)*Veh.Prop.kSj(5), -Veh.Prop.kSj(1), -Veh.Prop.kSj(2), -Veh.Prop.kSj(3), -Veh.Prop.kSj(4), -Veh.Prop.kSj(5)]; ...
    [Veh.Prop.bi(1)*Veh.Prop.kSj(3) + Veh.Prop.bi(1)*Veh.Prop.kSj(4) + Veh.Prop.bi(1)*Veh.Prop.kSj(5) + Veh.Prop.dj(1)*Veh.Prop.kSj(1) + Veh.Prop.dj(2)*Veh.Prop.kSj(2), Veh.Prop.bi(1)^2*Veh.Prop.kSj(3) + Veh.Prop.bi(1)^2*Veh.Prop.kSj(4) + Veh.Prop.bi(1)^2*Veh.Prop.kSj(5) + Veh.Prop.dj(1)^2*Veh.Prop.kSj(1) + Veh.Prop.dj(2)^2*Veh.Prop.kSj(2), Veh.Prop.ai(2)*Veh.Prop.bi(1)*Veh.Prop.kSj(3) + Veh.Prop.ai(2)*Veh.Prop.bi(1)*Veh.Prop.kSj(4) + Veh.Prop.ai(2)*Veh.Prop.bi(1)*Veh.Prop.kSj(5) + Veh.Prop.bi(1)*Veh.Prop.dj(3)*Veh.Prop.kSj(3) + Veh.Prop.bi(1)*Veh.Prop.dj(4)*Veh.Prop.kSj(4) + Veh.Prop.bi(1)*Veh.Prop.dj(5)*Veh.Prop.kSj(5), -Veh.Prop.dj(1)*Veh.Prop.kSj(1), -Veh.Prop.dj(2)*Veh.Prop.kSj(2), -Veh.Prop.bi(1)*Veh.Prop.kSj(3), -Veh.Prop.bi(1)*Veh.Prop.kSj(4), -Veh.Prop.bi(1)*Veh.Prop.kSj(5)]; ...
    [Veh.Prop.ai(2)*Veh.Prop.kSj(3) + Veh.Prop.ai(2)*Veh.Prop.kSj(4) + Veh.Prop.ai(2)*Veh.Prop.kSj(5) + Veh.Prop.dj(3)*Veh.Prop.kSj(3) + Veh.Prop.dj(4)*Veh.Prop.kSj(4) + Veh.Prop.dj(5)*Veh.Prop.kSj(5), Veh.Prop.ai(2)*Veh.Prop.bi(1)*Veh.Prop.kSj(3) + Veh.Prop.ai(2)*Veh.Prop.bi(1)*Veh.Prop.kSj(4) + Veh.Prop.ai(2)*Veh.Prop.bi(1)*Veh.Prop.kSj(5) + Veh.Prop.bi(1)*Veh.Prop.dj(3)*Veh.Prop.kSj(3) + Veh.Prop.bi(1)*Veh.Prop.dj(4)*Veh.Prop.kSj(4) + Veh.Prop.bi(1)*Veh.Prop.dj(5)*Veh.Prop.kSj(5), Veh.Prop.ai(2)^2*Veh.Prop.kSj(3) + Veh.Prop.ai(2)^2*Veh.Prop.kSj(4) + Veh.Prop.ai(2)^2*Veh.Prop.kSj(5) + Veh.Prop.dj(3)^2*Veh.Prop.kSj(3) + Veh.Prop.dj(4)^2*Veh.Prop.kSj(4) + Veh.Prop.dj(5)^2*Veh.Prop.kSj(5) + 2*Veh.Prop.ai(2)*Veh.Prop.dj(3)*Veh.Prop.kSj(3) + 2*Veh.Prop.ai(2)*Veh.Prop.dj(4)*Veh.Prop.kSj(4) + 2*Veh.Prop.ai(2)*Veh.Prop.dj(5)*Veh.Prop.kSj(5), 0, 0, - Veh.Prop.ai(2)*Veh.Prop.kSj(3) - Veh.Prop.dj(3)*Veh.Prop.kSj(3), - Veh.Prop.ai(2)*Veh.Prop.kSj(4) - Veh.Prop.dj(4)*Veh.Prop.kSj(4), - Veh.Prop.ai(2)*Veh.Prop.kSj(5) - Veh.Prop.dj(5)*Veh.Prop.kSj(5)]; ...
    [-Veh.Prop.kSj(1), -Veh.Prop.dj(1)*Veh.Prop.kSj(1), 0, Veh.Prop.kSj(1) + Veh.Prop.kTk(1), 0, 0, 0, 0]; ...
    [-Veh.Prop.kSj(2), -Veh.Prop.dj(2)*Veh.Prop.kSj(2), 0, 0, Veh.Prop.kSj(2) + Veh.Prop.kTk(2), 0, 0, 0]; ...
    [-Veh.Prop.kSj(3), -Veh.Prop.bi(1)*Veh.Prop.kSj(3), - Veh.Prop.ai(2)*Veh.Prop.kSj(3) - Veh.Prop.dj(3)*Veh.Prop.kSj(3), 0, 0, Veh.Prop.kSj(3) + Veh.Prop.kTk(3), 0, 0]; ...
    [-Veh.Prop.kSj(4), -Veh.Prop.bi(1)*Veh.Prop.kSj(4), - Veh.Prop.ai(2)*Veh.Prop.kSj(4) - Veh.Prop.dj(4)*Veh.Prop.kSj(4), 0, 0, 0, Veh.Prop.kSj(4) + Veh.Prop.kTk(4), 0]; ...
    [-Veh.Prop.kSj(5), -Veh.Prop.bi(1)*Veh.Prop.kSj(5), - Veh.Prop.ai(2)*Veh.Prop.kSj(5) - Veh.Prop.dj(5)*Veh.Prop.kSj(5), 0, 0, 0, 0, Veh.Prop.kSj(5) + Veh.Prop.kTk(5)]];
 
% -- Force vector to calculate static response --
% Note: When using this vector, multiply it by the gravity. Following the sign criteria defined here
%   gravity has negative value. The numerical value to use is grav = -9.81 m/s^2
Veh.Static.F_vector_no_grav = [Veh.Prop.mBi(1) + Veh.Prop.mBi(2), Veh.Prop.bi(1)*Veh.Prop.mBi(2), Veh.Prop.ai(2)*Veh.Prop.mBi(2), Veh.Prop.mGj(1), Veh.Prop.mGj(2), Veh.Prop.mGj(3), Veh.Prop.mGj(4), Veh.Prop.mGj(5)];
 
% -- Nodal disp. to wheel disp. relation --
Veh.SysM.N2w = ...
    [[0, 0, 0, 1, 0, 0, 0, 0]; ...
    [0, 0, 0, 0, 1, 0, 0, 0]; ...
    [0, 0, 0, 0, 0, 1, 0, 0]; ...
    [0, 0, 0, 0, 0, 0, 1, 0]; ...
    [0, 0, 0, 0, 0, 0, 0, 1]];
 
% ---- End of function ----